spring.application.name=PAF-Assigment
spring.data.mongodb.database=Fap
spring.data.mongodb.uri=mongodb+srv://Oshan:Oshan123@fap.xnlwigf.mongodb.net/?retryWrites=true&w=majority&appName=Fap
server.port=4000

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=272976157951-undj990qvlttvof7ooj8v8pt2fsdi8a4.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/oauth2/callback/{registrationId}


