spring.application.name=PAF-Assigment
spring.data.mongodb.database=Fap
spring.data.mongodb.uri=mongodb+srv://Oshan:Oshan123@fap.xnlwigf.mongodb.net/?retryWrites=true&w=majority&appName=Fap
server.port= 4000